stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-q --batch-mode --errors --fail-at-end"

cache:
  key: maven-cache
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  image: node:20-alpine
  variables:
    # Gán trực tiếp biến từ GitLab vào môi trường của Job
    RAILWAY_TOKEN: $RAILWAY_TOKEN
  script:
    - npm i -g @railway/cli
    # Sử dụng lệnh up đơn giản nhất, CLI sẽ tự hiểu Token từ biến môi trường trên
    - railway up --project "706d1859-3b8f-41d7-825f-68341abf47d8" --service "d0911cf4-bf23-45cd-b420-ed738635d172" --environment "c854a86d-2b0f-4ced-94be-ddfa3780fd90" --detach