stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-q --batch-mode --errors --fail-at-end"

cache:
  key: maven-cache
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  image: node:20-alpine
  before_script:
    - npm i -g @railway/cli
  script:
    # Không cần login riêng nếu dùng RAILWAY_TOKEN trực tiếp trong các lệnh sau
    - railway up --token $RAILWAY_TOKEN --project "$RAILWAY_PROJECT_ID" --service "$RAILWAY_SERVICE_ID" --detach
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always