spring.datasource.url=jdbc:postgresql://localhost:5435/book_review
spring.datasource.username=postgres
spring.datasource.password=quangtruong1

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
